[book]
authors = ["Aedius"]
language = "en"
multilingual = false
src = "src"
title = "Game rules for the Horfimbor project"

[output.html]
default-theme = "rust"

[output.html.print]
enable = false

[preprocessor.footnote]

[preprocessor.yapp]